In [ ]:
pip install yfinance

In [ ]:
pip install newsapi-python

In [2]:
# Dependencies
import yfinance as yf
import requests
import json
import pandas as pd
from config import api_key
from bs4 import BeautifulSoup
import requests

In [3]:
# url for the scraping of the top 100 stocks
stock_url = 'https://robinhood.com/collections/100-most-popular'

In [4]:
tables = pd.read_html(stock_url)
tables

[                  Name Symbol    Price   Today Market Cap  Popularity  \
 0      Aurora Cannabis    ACB    $0.99  15.38%      1.55B      680269
 1                 Ford      F    $5.97   8.01%     27.64B      415529
 2                   GE     GE    $8.25  12.23%     95.09B      348523
 3            Microsoft   MSFT  $153.86   4.77%      1.25T      333419
 4                GoPro   GPRO    $3.30  10.81%    613.84M      302060
 ..                 ...    ...      ...     ...        ...         ...
 95              CRISPR   CRSP   $43.00  15.45%      3.11B       27643
 96              Twilio   TWLO   $92.97   8.65%     14.73B       27566
 97              AbbVie   ABBV   $86.95   2.11%    129.53B       27517
 98     SmileDirectClub    SDC    $6.99  13.28%      2.91B       27485
 99  Limelight Networks   LLNW    $4.53   9.58%    570.53M       26905

    Analyst Ratings
 0          14% Buy
 1          33% Buy
 2          57% Buy
 3          94% Buy
 4              â
 ..             ...
 95         73% Buy
 96         89% Buy
 97         58% Buy
 98         67% Buy
 99             â

 [100 rows x 7 columns]]

In [5]:
df = tables[0]
df.columns = ['Name', 'Symbol', 'Price', 'Today', 
              'Market Cap', 'Popularity', 
              'Analyst Ratings']
df.head(10)

,Name,Symbol,Price,Today,Market Cap,Popularity,Analyst Ratings
0,Aurora Cannabis,ACB,$0.99,15.38%,1.55B,680269,14% Buy
1,Ford,F,$5.97,8.01%,27.64B,415529,33% Buy
2,GE,GE,$8.25,12.23%,95.09B,348523,57% Buy
3,Microsoft,MSFT,$153.86,4.77%,1.25T,333419,94% Buy
4,GoPro,GPRO,$3.30,10.81%,613.84M,302060,â
5,Apple,AAPL,$271.75,5.98%,1.27T,265105,62% Buy
6,Fitbit,FIT,$6.11,1.77%,1.70B,264896,0% Buy
7,Disney,DIS,$106.50,7.61%,210.24B,248713,74% Buy
8,Plug Power,PLUG,$3.88,10.39%,1.38B,236092,86% Buy
9,AMD,AMD,$43.76,9.94%,54.68B,202830,32% Buy

In [6]:
from newsapi import NewsApiClient

# Init
newsapi = NewsApiClient(api_key='1ed5d22def014dc9b9a2e4446c34dc0c')

In [7]:
# # /v2/everything
# all_articles = newsapi.get_everything(q='msft',
#                                       from_param='2020-02-08',
#                                       to='2020-03-07',
#                                       language='en',
#                                       sort_by='relevancy')

In [8]:
# print(all_articles)

In [9]:
# all_articles['totalResults']

In [10]:
tables

[                  Name Symbol    Price   Today Market Cap  Popularity  \
 0      Aurora Cannabis    ACB    $0.99  15.38%      1.55B      680269
 1                 Ford      F    $5.97   8.01%     27.64B      415529
 2                   GE     GE    $8.25  12.23%     95.09B      348523
 3            Microsoft   MSFT  $153.86   4.77%      1.25T      333419
 4                GoPro   GPRO    $3.30  10.81%    613.84M      302060
 ..                 ...    ...      ...     ...        ...         ...
 95              CRISPR   CRSP   $43.00  15.45%      3.11B       27643
 96              Twilio   TWLO   $92.97   8.65%     14.73B       27566
 97              AbbVie   ABBV   $86.95   2.11%    129.53B       27517
 98     SmileDirectClub    SDC    $6.99  13.28%      2.91B       27485
 99  Limelight Networks   LLNW    $4.53   9.58%    570.53M       26905

    Analyst Ratings
 0          14% Buy
 1          33% Buy
 2          57% Buy
 3          94% Buy
 4              â
 ..             ...
 95         73% Buy
 96         89% Buy
 97         58% Buy
 98         67% Buy
 99             â

 [100 rows x 7 columns]]

In [11]:
df_symbols = tables[0]
df_symbols.columns = ['Name', 'Symbol', 'Price', 'Today', 'Market Cap', 'Popularity', 'Analyst Ratings']
df_symbols.head(10)

,Name,Symbol,Price,Today,Market Cap,Popularity,Analyst Ratings
0,Aurora Cannabis,ACB,$0.99,15.38%,1.55B,680269,14% Buy
1,Ford,F,$5.97,8.01%,27.64B,415529,33% Buy
2,GE,GE,$8.25,12.23%,95.09B,348523,57% Buy
3,Microsoft,MSFT,$153.86,4.77%,1.25T,333419,94% Buy
4,GoPro,GPRO,$3.30,10.81%,613.84M,302060,â
5,Apple,AAPL,$271.75,5.98%,1.27T,265105,62% Buy
6,Fitbit,FIT,$6.11,1.77%,1.70B,264896,0% Buy
7,Disney,DIS,$106.50,7.61%,210.24B,248713,74% Buy
8,Plug Power,PLUG,$3.88,10.39%,1.38B,236092,86% Buy
9,AMD,AMD,$43.76,9.94%,54.68B,202830,32% Buy

In [12]:
df_symbols = df_symbols.drop(columns=['Name', 'Price', 'Today', 
              'Market Cap', 'Popularity', 
              'Analyst Ratings'])
df_symbols.head()

  Symbol
0    ACB
1      F
2     GE
3   MSFT
4   GPRO

In [13]:
# symbol_list = df_symbol.tolist()
# print (symbol_list)

symbol_list = df["Symbol"].tolist()
print(symbol_list)

['ACB', 'F', 'GE', 'MSFT', 'GPRO', 'AAPL', 'FIT', 'DIS', 'PLUG', 'AMD', 'SNAP', 'CRON', 'CGC', 'HEXO', 'TSLA', 'CHK', 'INO', 'FB', 'BAC', 'UBER', 'ZNGA', 'BABA', 'TWTR', 'NIO', 'AMZN', 'T', 'SBUX', 'APHA', 'GRPN', 'S', 'NVDA', 'NFLX', 'SPCE', 'KO', 'VSLR', 'VOO', 'NOK', 'SQ', 'BYND', 'SIRI', 'V', 'WORK', 'CPRX', 'LYFT', 'NKE', 'SPY', 'NTDOY', 'FCEL', 'MRNA', 'CRBP', 'INTC', 'BA', 'OGI', 'ATVI', 'GLUU', 'GM', 'NRZ', 'AUY', 'TLRY', 'CSCO', 'MU', 'LK', 'TCEHY', 'BRK.B', 'VKTX', 'ROKU', 'DAL', 'VTI', 'PENN', 'PYPL', 'OPK', 'AAL', 'MJ', 'PFE', 'CRM', 'DNR', 'GOOGL', 'SNE', 'WMT', 'PCG', 'VZ', 'XOM', 'ENPH', 'PINS', 'SHOP', 'SPHD', 'NVAX', 'COST', 'IQ', 'GILD', 'BILI', 'PTON', 'ZM', 'DBX', 'JD', 'CRSP', 'TWLO', 'ABBV', 'SDC', 'LLNW']

In [ ]:
# /v2/everything

ag_results = []
for symbols in symbol_list:
    

    every_articles = newsapi.get_everything(q= (symbols),
                                          from_param='2020-02-09',
                                          to='2020-03-08',
                                          language='en',
                                          sort_by='relevancy')
    results = {
        "symbol": symbols,
        "article_count": every_articles['totalResults']
    }
    ag_results.append(results)
new_data = pd.DataFrame(ag_results)

new_data.head()
    
# every_articles['totalResults']

In [ ]:
new_data

In [ ]:
new_data.to_csv("final_counts.csv", index = False, header = True)

In [ ]:
msft = yf.Ticker("MSFT")
msft.history(period="max")

In [27]:
df_symbols.replace('BRK.B','BRK-B',inplace=True)
df_symbols
symbol_list = df_symbols["Symbol"].tolist()
print(symbol_list)

['ACB', 'F', 'GE', 'MSFT', 'GPRO', 'AAPL', 'FIT', 'DIS', 'PLUG', 'AMD', 'SNAP', 'CRON', 'CGC', 'HEXO', 'TSLA', 'CHK', 'INO', 'FB', 'BAC', 'UBER', 'ZNGA', 'BABA', 'TWTR', 'NIO', 'AMZN', 'T', 'SBUX', 'APHA', 'GRPN', 'S', 'NVDA', 'NFLX', 'SPCE', 'KO', 'VSLR', 'VOO', 'NOK', 'SQ', 'BYND', 'SIRI', 'V', 'WORK', 'CPRX', 'LYFT', 'NKE', 'SPY', 'NTDOY', 'FCEL', 'MRNA', 'CRBP', 'INTC', 'BA', 'OGI', 'ATVI', 'GLUU', 'GM', 'NRZ', 'AUY', 'TLRY', 'CSCO', 'MU', 'LK', 'TCEHY', 'BRK-B', 'VKTX', 'ROKU', 'DAL', 'VTI', 'PENN', 'PYPL', 'OPK', 'AAL', 'MJ', 'PFE', 'CRM', 'DNR', 'GOOGL', 'SNE', 'WMT', 'PCG', 'VZ', 'XOM', 'ENPH', 'PINS', 'SHOP', 'SPHD', 'NVAX', 'COST', 'IQ', 'GILD', 'BILI', 'PTON', 'ZM', 'DBX', 'JD', 'CRSP', 'TWLO', 'ABBV', 'SDC', 'LLNW']

In [69]:
ag_stock = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close","Volume", "Divendends", "Stock Splits",\
                                "Symbol"])
symbols

'LLNW'

In [71]:
for symbols in symbol_list:
    results = yf.Ticker(symbols)
    stock_data = results.history(period="max")
    symbol_df = pd.DataFrame(stock_data)
    symbol_df['Symbol'] = symbols
    symbol_df['Date'] = symbol_df.index
    # drop index
    symbol_df.reset_index(drop=True)
    # append with out index 
    ag_stock = ag_stock.append(symbol_df,ignore_index=True)

In [72]:
ag_stock

,Close,Date,Divendends,Dividends,High,Low,Open,Stock Splits,Symbol,Volume
0,40.9004,2000-01-03,NaN,0.0,40.9004,40.9004,39.8277,0,ACB,0
1,40.8898,2000-01-04,NaN,0.0,40.8898,40.8898,40.8898,0,ACB,0
2,39.5622,2000-01-05,NaN,0.0,39.5622,39.5622,39.5622,0,ACB,0
3,39.2967,2000-01-06,NaN,0.0,39.2967,39.2967,39.2967,0,ACB,0
4,39.8277,2000-01-07,NaN,0.0,39.8277,39.8277,39.2967,0,ACB,0
...,...,...,...,...,...,...,...,...,...,...
460258,4.8200,2020-03-03,NaN,0.0,5.2200,4.7700,5.0200,0,LLNW,2013800
460259,5.0500,2020-03-04,NaN,0.0,5.1100,4.8400,4.9100,0,LLNW,1597300
460260,4.9700,2020-03-05,NaN,0.0,5.0900,4.8600,4.9400,0,LLNW,1116700
460261,5.0100,2020-03-06,NaN,0.0,5.2400,4.8600,4.9200,0,LLNW,941300
460262,4.5300,2020-03-09,NaN,0.0,4.8200,4.4724,4.6400,0,LLNW,966955

In [73]:
ag_stock.to_csv("final_stockresults.csv", index = False, header = True)